abufsrc@Music0=outputs=1:map=1,asubgraph@Convert=inputs=1:outputs=1:map=1,alsasink@pcm0p=inputs=1:devname=pcm0p:format=s16:sample_rate=48000:ch_layout=stereo
<subgraph>Convert:aresample=48000:osf=s16:ochl=stereo
