# SPDX-License-Identifier: Apache-2.0
include $(APPDIR)/Make.defs
PROGNAME = s31simd
PRIORITY = 100
STACKSIZE = 8192
MODULE = $(CONFIG_EXAMPLES_S31SIMD)
MAINSRC = s31simd_main.c
ASRCS = s31simd_ops.S
include $(APPDIR)/Application.mk
